name: clothing_store_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.2
  image: ^3.3.0
  image_picker: ^1.0.4
  image_cropper: ^1.3.0
  get: 4.6.6
  http: ^1.1.0
  webview_flutter: ^4.4.1
  flutter_staggered_grid_view: ^0.7.0
  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  # shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  # flutter_launcher_icons: ^0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

