// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfi_edgSTXle1JijVPSDeUYIF5XnJy-Q0',
    appId: '1:358671433827:web:d35fb01804f86839c53856',
    messagingSenderId: '358671433827',
    projectId: 'clothing-store-51da9',
    authDomain: 'clothing-store-51da9.firebaseapp.com',
    storageBucket: 'clothing-store-51da9.appspot.com',
    measurementId: 'G-9MBKM8GHT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH0ikBk08Ma28Yr8mhrloMqeCtEYW9Z_s',
    appId: '1:358671433827:android:22626f47ae543f83c53856',
    messagingSenderId: '358671433827',
    projectId: 'clothing-store-51da9',
    storageBucket: 'clothing-store-51da9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgShLwfh9ceOzcZX-qMSWzmaNzaZZk12g',
    appId: '1:358671433827:ios:984885a2e865dce3c53856',
    messagingSenderId: '358671433827',
    projectId: 'clothing-store-51da9',
    storageBucket: 'clothing-store-51da9.appspot.com',
    iosBundleId: 'com.example.clothingStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgShLwfh9ceOzcZX-qMSWzmaNzaZZk12g',
    appId: '1:358671433827:ios:58f286db742eb6ddc53856',
    messagingSenderId: '358671433827',
    projectId: 'clothing-store-51da9',
    storageBucket: 'clothing-store-51da9.appspot.com',
    iosBundleId: 'com.example.clothingStoreApp.RunnerTests',
  );
}
